In [ ]:
import  pandas as pd

In [ ]:

data={
    "Name":["Amit","Riya","Rahul","Priya","Karan"],
    "Age":[20,21,20,22,21],
    "Department":["CSE","IT","CSE","ECE","IT"],
    "Marks":[85,90,78,88,76]
}
df=pd.DataFrame(data)
df

    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

In [ ]:
irs=pd.read_csv("/content/Iris.csv")
irs.head(7)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa

In [ ]:
#inspection of data set
iris.head()
iris.tail()
print("shape:",iris.shape)
print("Data Type:",iris.dtypes)
print(iris.isnull().sum())

shape: (150, 6)
Data Type: Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object
Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
iris.to_csv

In [ ]:
df.

convert DF to CSV

In [ ]:
df.to_csv("students.csv",index=False)

In [ ]:
df_new=pd.read_csv("students.csv")

In [ ]:
df_new.head()

    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

Save and Load Excel

In [ ]:
iris.to_excel("iris_output.xlsx",index=False)

In [ ]:
iris_excel=pd.read_excel("/content/iris_output.xlsx")

In [ ]:
iris_excel.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Save and Loan JSON

In [ ]:
iris.to_json("iris_output.json",orient="records",indent=4)

In [ ]:
iris_json=pd.read_json("/content/iris_output.json")

In [ ]:
iris_json.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
with open("iris_output.json","r") as file:
  print(file.read())

[
    {
        "Id":1,
        "SepalLengthCm":5.1,
        "SepalWidthCm":3.5,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":2,
        "SepalLengthCm":4.9,
        "SepalWidthCm":3.0,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":3,
        "SepalLengthCm":4.7,
        "SepalWidthCm":3.2,
        "PetalLengthCm":1.3,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":4,
        "SepalLengthCm":4.6,
        "SepalWidthCm":3.1,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":5,
        "SepalLengthCm":5.0,
        "SepalWidthCm":3.6,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":6,
        "SepalLengthCm":5.4,
        "SepalWidthCm":3.9,
        "PetalLengthCm":1.7,
        "PetalWidthCm":0.4,
        "Species":"Iris-setosa"
    },
    {
        "Id":7,
        "SepalLengthCm":4.6,
        "SepalWidthCm":3.4,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.3,
        "Species":"Iris-setosa"
    },
    {
        "Id":8,
        "SepalLengthCm":5.0,
        "SepalWidthCm":3.4,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":9,
        "SepalLengthCm":4.4,
        "SepalWidthCm":2.9,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":10,
        "SepalLengthCm":4.9,
        "SepalWidthCm":3.1,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.1,
        "Species":"Iris-setosa"
    },
    {
        "Id":11,
        "SepalLengthCm":5.4,
        "SepalWidthCm":3.7,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":12,
        "SepalLengthCm":4.8,
        "SepalWidthCm":3.4,
        "PetalLengthCm":1.6,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":13,
        "SepalLengthCm":4.8,
        "SepalWidthCm":3.0,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.1,
        "Species":"Iris-setosa"
    },
    {
        "Id":14,
        "SepalLengthCm":4.3,
        "SepalWidthCm":3.0,
        "PetalLengthCm":1.1,
        "PetalWidthCm":0.1,
        "Species":"Iris-setosa"
    },
    {
        "Id":15,
        "SepalLengthCm":5.8,
        "SepalWidthCm":4.0,
        "PetalLengthCm":1.2,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":16,
        "SepalLengthCm":5.7,
        "SepalWidthCm":4.4,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.4,
        "Species":"Iris-setosa"
    },
    {
        "Id":17,
        "SepalLengthCm":5.4,
        "SepalWidthCm":3.9,
        "PetalLengthCm":1.3,
        "PetalWidthCm":0.4,
        "Species":"Iris-setosa"
    },
    {
        "Id":18,
        "SepalLengthCm":5.1,
        "SepalWidthCm":3.5,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.3,
        "Species":"Iris-setosa"
    },
    {
        "Id":19,
        "SepalLengthCm":5.7,
        "SepalWidthCm":3.8,
        "PetalLengthCm":1.7,
        "PetalWidthCm":0.3,
        "Species":"Iris-setosa"
    },
    {
        "Id":20,
        "SepalLengthCm":5.1,
        "SepalWidthCm":3.8,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.3,
        "Species":"Iris-setosa"
    },
    {
        "Id":21,
        "SepalLengthCm":5.4,
        "SepalWidthCm":3.4,
        "PetalLengthCm":1.7,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":22,
        "SepalLengthCm":5.1,
        "SepalWidthCm":3.7,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.4,
        "Species":"Iris-setosa"
    },
    {
        "Id":23,
        "SepalLengthCm":4.6,
        "SepalWidthCm":3.6,
        "PetalLengthCm":1.0,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":24,
        "SepalLengthCm":5.1,
        "SepalWidthCm":3.3,
        "PetalLengthCm":1.7,
        "PetalWidthCm":0.5,
        "Species":"Iris-setosa"
    },
    {
        "Id":25,
        "SepalLengthCm":4.8,
        "SepalWidthCm":3.4,
        "PetalLengthCm":1.9,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":26,
        "SepalLengthCm":5.0,
        "SepalWidthCm":3.0,
        "PetalLengthCm":1.6,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":27,
        "SepalLengthCm":5.0,
        "SepalWidthCm":3.4,
        "PetalLengthCm":1.6,
        "PetalWidthCm":0.4,
        "Species":"Iris-setosa"
    },
    {
        "Id":28,
        "SepalLengthCm":5.2,
        "SepalWidthCm":3.5,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":29,
        "SepalLengthCm":5.2,
        "SepalWidthCm":3.4,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":30,
        "SepalLengthCm":4.7,
        "SepalWidthCm":3.2,
        "PetalLengthCm":1.6,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":31,
        "SepalLengthCm":4.8,
        "SepalWidthCm":3.1,
        "PetalLengthCm":1.6,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":32,
        "SepalLengthCm":5.4,
        "SepalWidthCm":3.4,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.4,
        "Species":"Iris-setosa"
    },
    {
        "Id":33,
        "SepalLengthCm":5.2,
        "SepalWidthCm":4.1,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.1,
        "Species":"Iris-setosa"
    },
    {
        "Id":34,
        "SepalLengthCm":5.5,
        "SepalWidthCm":4.2,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":35,
        "SepalLengthCm":4.9,
        "SepalWidthCm":3.1,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.1,
        "Species":"Iris-setosa"
    },
    {
        "Id":36,
        "SepalLengthCm":5.0,
        "SepalWidthCm":3.2,
        "PetalLengthCm":1.2,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":37,
        "SepalLengthCm":5.5,
        "SepalWidthCm":3.5,
        "PetalLengthCm":1.3,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":38,
        "SepalLengthCm":4.9,
        "SepalWidthCm":3.1,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.1,
        "Species":"Iris-setosa"
    },
    {
        "Id":39,
        "SepalLengthCm":4.4,
        "SepalWidthCm":3.0,
        "PetalLengthCm":1.3,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":40,
        "SepalLengthCm":5.1,
        "SepalWidthCm":3.4,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":41,
        "SepalLengthCm":5.0,
        "SepalWidthCm":3.5,
        "PetalLengthCm":1.3,
        "PetalWidthCm":0.3,
        "Species":"Iris-setosa"
    },
    {
        "Id":42,
        "SepalLengthCm":4.5,
        "SepalWidthCm":2.3,
        "PetalLengthCm":1.3,
        "PetalWidthCm":0.3,
        "Species":"Iris-setosa"
    },
    {
        "Id":43,
        "SepalLengthCm":4.4,
        "SepalWidthCm":3.2,
        "PetalLengthCm":1.3,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":44,
        "SepalLengthCm":5.0,
        "SepalWidthCm":3.5,
        "PetalLengthCm":1.6,
        "PetalWidthCm":0.6,
        "Species":"Iris-setosa"
    },
    {
        "Id":45,
        "SepalLengthCm":5.1,
        "SepalWidthCm":3.8,
        "PetalLengthCm":1.9,
        "PetalWidthCm":0.4,
        "Species":"Iris-setosa"
    },
    {
        "Id":46,
        "SepalLengthCm":4.8,
        "SepalWidthCm":3.0,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.3,
        "Species":"Iris-setosa"
    },
    {
        "Id":47,
        "SepalLengthCm":5.1,
        "SepalWidthCm":3.8,
        "PetalLengthCm":1.6,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":48,
        "SepalLengthCm":4.6,
        "SepalWidthCm":3.2,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":49,
        "SepalLengthCm":5.3,
        "SepalWidthCm":3.7,
        "PetalLengthCm":1.5,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":50,
        "SepalLengthCm":5.0,
        "SepalWidthCm":3.3,
        "PetalLengthCm":1.4,
        "PetalWidthCm":0.2,
        "Species":"Iris-setosa"
    },
    {
        "Id":51,
        "SepalLengthCm":7.0,
        "SepalWidthCm":3.2,
        "PetalLengthCm":4.7,
        "PetalWidthCm":1.4,
        "Species":"Iris-versicolor"
    },
    {
        "Id":52,
        "SepalLengthCm":6.4,
        "SepalWidthCm":3.2,
        "PetalLengthCm":4.5,
        "PetalWidthCm":1.5,
        "Species":"Iris-versicolor"
    },
    {
        "Id":53,
        "SepalLengthCm":6.9,
        "SepalWidthCm":3.1,
        "PetalLengthCm":4.9,
        "PetalWidthCm":1.5,
        "Species":"Iris-versicolor"
    },
    {
        "Id":54,
        "SepalLengthCm":5.5,
        "SepalWidthCm":2.3,
        "PetalLengthCm":4.0,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":55,
        "SepalLengthCm":6.5,
        "SepalWidthCm":2.8,
        "PetalLengthCm":4.6,
        "PetalWidthCm":1.5,
        "Species":"Iris-versicolor"
    },
    {
        "Id":56,
        "SepalLengthCm":5.7,
        "SepalWidthCm":2.8,
        "PetalLengthCm":4.5,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":57,
        "SepalLengthCm":6.3,
        "SepalWidthCm":3.3,
        "PetalLengthCm":4.7,
        "PetalWidthCm":1.6,
        "Species":"Iris-versicolor"
    },
    {
        "Id":58,
        "SepalLengthCm":4.9,
        "SepalWidthCm":2.4,
        "PetalLengthCm":3.3,
        "PetalWidthCm":1.0,
        "Species":"Iris-versicolor"
    },
    {
        "Id":59,
        "SepalLengthCm":6.6,
        "SepalWidthCm":2.9,
        "PetalLengthCm":4.6,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":60,
        "SepalLengthCm":5.2,
        "SepalWidthCm":2.7,
        "PetalLengthCm":3.9,
        "PetalWidthCm":1.4,
        "Species":"Iris-versicolor"
    },
    {
        "Id":61,
        "SepalLengthCm":5.0,
        "SepalWidthCm":2.0,
        "PetalLengthCm":3.5,
        "PetalWidthCm":1.0,
        "Species":"Iris-versicolor"
    },
    {
        "Id":62,
        "SepalLengthCm":5.9,
        "SepalWidthCm":3.0,
        "PetalLengthCm":4.2,
        "PetalWidthCm":1.5,
        "Species":"Iris-versicolor"
    },
    {
        "Id":63,
        "SepalLengthCm":6.0,
        "SepalWidthCm":2.2,
        "PetalLengthCm":4.0,
        "PetalWidthCm":1.0,
        "Species":"Iris-versicolor"
    },
    {
        "Id":64,
        "SepalLengthCm":6.1,
        "SepalWidthCm":2.9,
        "PetalLengthCm":4.7,
        "PetalWidthCm":1.4,
        "Species":"Iris-versicolor"
    },
    {
        "Id":65,
        "SepalLengthCm":5.6,
        "SepalWidthCm":2.9,
        "PetalLengthCm":3.6,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":66,
        "SepalLengthCm":6.7,
        "SepalWidthCm":3.1,
        "PetalLengthCm":4.4,
        "PetalWidthCm":1.4,
        "Species":"Iris-versicolor"
    },
    {
        "Id":67,
        "SepalLengthCm":5.6,
        "SepalWidthCm":3.0,
        "PetalLengthCm":4.5,
        "PetalWidthCm":1.5,
        "Species":"Iris-versicolor"
    },
    {
        "Id":68,
        "SepalLengthCm":5.8,
        "SepalWidthCm":2.7,
        "PetalLengthCm":4.1,
        "PetalWidthCm":1.0,
        "Species":"Iris-versicolor"
    },
    {
        "Id":69,
        "SepalLengthCm":6.2,
        "SepalWidthCm":2.2,
        "PetalLengthCm":4.5,
        "PetalWidthCm":1.5,
        "Species":"Iris-versicolor"
    },
    {
        "Id":70,
        "SepalLengthCm":5.6,
        "SepalWidthCm":2.5,
        "PetalLengthCm":3.9,
        "PetalWidthCm":1.1,
        "Species":"Iris-versicolor"
    },
    {
        "Id":71,
        "SepalLengthCm":5.9,
        "SepalWidthCm":3.2,
        "PetalLengthCm":4.8,
        "PetalWidthCm":1.8,
        "Species":"Iris-versicolor"
    },
    {
        "Id":72,
        "SepalLengthCm":6.1,
        "SepalWidthCm":2.8,
        "PetalLengthCm":4.0,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":73,
        "SepalLengthCm":6.3,
        "SepalWidthCm":2.5,
        "PetalLengthCm":4.9,
        "PetalWidthCm":1.5,
        "Species":"Iris-versicolor"
    },
    {
        "Id":74,
        "SepalLengthCm":6.1,
        "SepalWidthCm":2.8,
        "PetalLengthCm":4.7,
        "PetalWidthCm":1.2,
        "Species":"Iris-versicolor"
    },
    {
        "Id":75,
        "SepalLengthCm":6.4,
        "SepalWidthCm":2.9,
        "PetalLengthCm":4.3,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":76,
        "SepalLengthCm":6.6,
        "SepalWidthCm":3.0,
        "PetalLengthCm":4.4,
        "PetalWidthCm":1.4,
        "Species":"Iris-versicolor"
    },
    {
        "Id":77,
        "SepalLengthCm":6.8,
        "SepalWidthCm":2.8,
        "PetalLengthCm":4.8,
        "PetalWidthCm":1.4,
        "Species":"Iris-versicolor"
    },
    {
        "Id":78,
        "SepalLengthCm":6.7,
        "SepalWidthCm":3.0,
        "PetalLengthCm":5.0,
        "PetalWidthCm":1.7,
        "Species":"Iris-versicolor"
    },
    {
        "Id":79,
        "SepalLengthCm":6.0,
        "SepalWidthCm":2.9,
        "PetalLengthCm":4.5,
        "PetalWidthCm":1.5,
        "Species":"Iris-versicolor"
    },
    {
        "Id":80,
        "SepalLengthCm":5.7,
        "SepalWidthCm":2.6,
        "PetalLengthCm":3.5,
        "PetalWidthCm":1.0,
        "Species":"Iris-versicolor"
    },
    {
        "Id":81,
        "SepalLengthCm":5.5,
        "SepalWidthCm":2.4,
        "PetalLengthCm":3.8,
        "PetalWidthCm":1.1,
        "Species":"Iris-versicolor"
    },
    {
        "Id":82,
        "SepalLengthCm":5.5,
        "SepalWidthCm":2.4,
        "PetalLengthCm":3.7,
        "PetalWidthCm":1.0,
        "Species":"Iris-versicolor"
    },
    {
        "Id":83,
        "SepalLengthCm":5.8,
        "SepalWidthCm":2.7,
        "PetalLengthCm":3.9,
        "PetalWidthCm":1.2,
        "Species":"Iris-versicolor"
    },
    {
        "Id":84,
        "SepalLengthCm":6.0,
        "SepalWidthCm":2.7,
        "PetalLengthCm":5.1,
        "PetalWidthCm":1.6,
        "Species":"Iris-versicolor"
    },
    {
        "Id":85,
        "SepalLengthCm":5.4,
        "SepalWidthCm":3.0,
        "PetalLengthCm":4.5,
        "PetalWidthCm":1.5,
        "Species":"Iris-versicolor"
    },
    {
        "Id":86,
        "SepalLengthCm":6.0,
        "SepalWidthCm":3.4,
        "PetalLengthCm":4.5,
        "PetalWidthCm":1.6,
        "Species":"Iris-versicolor"
    },
    {
        "Id":87,
        "SepalLengthCm":6.7,
        "SepalWidthCm":3.1,
        "PetalLengthCm":4.7,
        "PetalWidthCm":1.5,
        "Species":"Iris-versicolor"
    },
    {
        "Id":88,
        "SepalLengthCm":6.3,
        "SepalWidthCm":2.3,
        "PetalLengthCm":4.4,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":89,
        "SepalLengthCm":5.6,
        "SepalWidthCm":3.0,
        "PetalLengthCm":4.1,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":90,
        "SepalLengthCm":5.5,
        "SepalWidthCm":2.5,
        "PetalLengthCm":4.0,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":91,
        "SepalLengthCm":5.5,
        "SepalWidthCm":2.6,
        "PetalLengthCm":4.4,
        "PetalWidthCm":1.2,
        "Species":"Iris-versicolor"
    },
    {
        "Id":92,
        "SepalLengthCm":6.1,
        "SepalWidthCm":3.0,
        "PetalLengthCm":4.6,
        "PetalWidthCm":1.4,
        "Species":"Iris-versicolor"
    },
    {
        "Id":93,
        "SepalLengthCm":5.8,
        "SepalWidthCm":2.6,
        "PetalLengthCm":4.0,
        "PetalWidthCm":1.2,
        "Species":"Iris-versicolor"
    },
    {
        "Id":94,
        "SepalLengthCm":5.0,
        "SepalWidthCm":2.3,
        "PetalLengthCm":3.3,
        "PetalWidthCm":1.0,
        "Species":"Iris-versicolor"
    },
    {
        "Id":95,
        "SepalLengthCm":5.6,
        "SepalWidthCm":2.7,
        "PetalLengthCm":4.2,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":96,
        "SepalLengthCm":5.7,
        "SepalWidthCm":3.0,
        "PetalLengthCm":4.2,
        "PetalWidthCm":1.2,
        "Species":"Iris-versicolor"
    },
    {
        "Id":97,
        "SepalLengthCm":5.7,
        "SepalWidthCm":2.9,
        "PetalLengthCm":4.2,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":98,
        "SepalLengthCm":6.2,
        "SepalWidthCm":2.9,
        "PetalLengthCm":4.3,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":99,
        "SepalLengthCm":5.1,
        "SepalWidthCm":2.5,
        "PetalLengthCm":3.0,
        "PetalWidthCm":1.1,
        "Species":"Iris-versicolor"
    },
    {
        "Id":100,
        "SepalLengthCm":5.7,
        "SepalWidthCm":2.8,
        "PetalLengthCm":4.1,
        "PetalWidthCm":1.3,
        "Species":"Iris-versicolor"
    },
    {
        "Id":101,
        "SepalLengthCm":6.3,
        "SepalWidthCm":3.3,
        "PetalLengthCm":6.0,
        "PetalWidthCm":2.5,
        "Species":"Iris-virginica"
    },
    {
        "Id":102,
        "SepalLengthCm":5.8,
        "SepalWidthCm":2.7,
        "PetalLengthCm":5.1,
        "PetalWidthCm":1.9,
        "Species":"Iris-virginica"
    },
    {
        "Id":103,
        "SepalLengthCm":7.1,
        "SepalWidthCm":3.0,
        "PetalLengthCm":5.9,
        "PetalWidthCm":2.1,
        "Species":"Iris-virginica"
    },
    {
        "Id":104,
        "SepalLengthCm":6.3,
        "SepalWidthCm":2.9,
        "PetalLengthCm":5.6,
        "PetalWidthCm":1.8,
        "Species":"Iris-virginica"
    },
    {
        "Id":105,
        "SepalLengthCm":6.5,
        "SepalWidthCm":3.0,
        "PetalLengthCm":5.8,
        "PetalWidthCm":2.2,
        "Species":"Iris-virginica"
    },
    {
        "Id":106,
        "SepalLengthCm":7.6,
        "SepalWidthCm":3.0,
        "PetalLengthCm":6.6,
        "PetalWidthCm":2.1,
        "Species":"Iris-virginica"
    },
    {
        "Id":107,
        "SepalLengthCm":4.9,
        "SepalWidthCm":2.5,
        "PetalLengthCm":4.5,
        "PetalWidthCm":1.7,
        "Species":"Iris-virginica"
    },
    {
        "Id":108,
        "SepalLengthCm":7.3,
        "SepalWidthCm":2.9,
        "PetalLengthCm":6.3,
        "PetalWidthCm":1.8,
        "Species":"Iris-virginica"
    },
    {
        "Id":109,
        "SepalLengthCm":6.7,
        "SepalWidthCm":2.5,
        "PetalLengthCm":5.8,
        "PetalWidthCm":1.8,
        "Species":"Iris-virginica"
    },
    {
        "Id":110,
        "SepalLengthCm":7.2,
        "SepalWidthCm":3.6,
        "PetalLengthCm":6.1,
        "PetalWidthCm":2.5,
        "Species":"Iris-virginica"
    },
    {
        "Id":111,
        "SepalLengthCm":6.5,
        "SepalWidthCm":3.2,
        "PetalLengthCm":5.1,
        "PetalWidthCm":2.0,
        "Species":"Iris-virginica"
    },
    {
        "Id":112,
        "SepalLengthCm":6.4,
        "SepalWidthCm":2.7,
        "PetalLengthCm":5.3,
        "PetalWidthCm":1.9,
        "Species":"Iris-virginica"
    },
    {
        "Id":113,

In [ ]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.13/dist-packages (23.0.1)

In [ ]:
iris.to_parquet("iris_output.parquet",index=False)

In [ ]:
iris_parquet=pd.read_parquet("iris_output.parquet")

In [ ]:
iris_parquet.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

#Load the dataset-Kaggle-downloaded,
#converted to zip to unzip
#uploaded in collab
#created a DataFrame-data->dataframe-
df
#loaded the dataset then read_csv
#print csv file
#inspected the dataset -head(),tail(),
#shape ,dtypes,describe(),info,isnull()
#2.create a DataFrame-convert to diff file formats
# csv,excel,json,parquet
#.to_csv
#.to_excel
#.to_json
#.to_parquet